version : '1.0'
services:
  plt-mysql:
    container_name: plt-mysql
    image: mysql:8.0
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=80M',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1'
    ]
    environment:
      MYSQL_DATABASE: 'plt'
      MYSQL_ROOT_PASSWORD: root123
  plt-redis:
    container_name: plt-redis
    image: redis
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/home/plt/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/plt/redis/redis.conf
  plt-nginx:
    container_name: plt-nginx
    image: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
#      - ./nginx/dist:/home/plt/front/plt-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
  plt-admin:
    container_name: plt-admin
    build:
      context: ./plt-admin
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - plt-mysql
      - plt-redis
    links:
      - plt-mysql
      - plt-redis