# 基础镜像
FROM nginx
# 创建目录
RUN mkdir -p /home/plt/front/plt-ui
# 指定路径
WORKDIR /home/plt/front/plt-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
ADD ./html/dist /home/plt/front/plt-ui
